apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qe11kxjlt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qe11kxjlt-python 
  name: qe11kxjlt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qe11kxjlt-python 
